version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Authorize GCloud Command Line Tool
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
      - run:
          name: Deploy To Google Cloud Functions
          command: |
            gcloud functions deploy $GCLOUD_FUNCTION_NAME \
              --entry-point tripsSlackAppEntrypoint \
              --runtime nodejs16 \
              --trigger-http \
              --source ./src/ \
              --project $GCLOUD_PROJECT

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only:
                - main